/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - send other docs to the sidebar
 * - specify the order of docs in sidebar
 *
 * Learn more: https://docusaurus.io/docs/sidebar
 */

import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  mainSidebar: [
    'introduction/index', // This will be the index page for introduction
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'generated-index',
        title: 'Introduction',
        description: 'Set the stage for physical AI and humanoid robotics.',
        slug: '/category/introduction',
      },
      items: [
        'introduction/what-is-physical-ai',
        'introduction/why-humanoid-robots',
        'introduction/book-overview',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2 Fundamentals',
      link: {
        type: 'generated-index',
        title: 'Module 1: ROS 2 Fundamentals for Robotics',
        description: 'Introduce ROS 2 as the robotic middleware.',
        slug: '/category/module-1-ros2',
      },
      items: [
        'module-1-ros2/ros2-concepts',
        'module-1-ros2/setting-up-environment',
        'module-1-ros2/basic-programming',
        'module-1-ros2/robot-description-format',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin Simulation',
      link: {
        type: 'generated-index',
        title: 'Module 2: Digital Twin Simulation (Gazebo & Unity)',
        description: 'Explore simulation environments for robotics development.',
        slug: '/category/module-2-digital-twin',
      },
      items: [
        'module-2-digital-twin/introduction-to-simulation',
        'module-2-digital-twin/creating-robot-models',
        'module-2-digital-twin/simulating-sensors-actuators',
        'module-2-digital-twin/ros2-integration-with-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain',
      link: {
        type: 'generated-index',
        title: 'Module 3: AI-Robot Brain (NVIDIA Isaac™)',
        description: 'Integrate NVIDIA Isaac for advanced AI perception.',
        slug: '/category/module-3-ai-robot-brain',
      },
      items: [
        'module-3-ai-robot-brain/isaac-ecosystem-overview',
        'module-3-ai-robot-brain/setting-up-isaac',
        'module-3-ai-robot-brain/object-detection-with-isaac',
        'module-3-ai-robot-brain/pose-estimation-tracking',
        'module-3-ai-robot-brain/navigation-path-planning',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA Integration',
      link: {
        type: 'generated-index',
        title: 'Module 4: Vision-Language-Action (VLA) Integration',
        description: 'Bridge perception and language for intuitive robot control.',
        slug: '/category/module-4-vla',
      },
      items: [
        'module-4-vla/introduction-to-vla',
        'module-4-vla/natural-language-understanding',
        'module-4-vla/action-generation',
        'module-4-vla/vla-frameworks-apis',
        'module-4-vla/ethical-considerations',
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      link: {
        type: 'generated-index',
        title: 'Capstone Project: Building a Humanoid AI System',
        description: 'Apply learned concepts to build a complete system.',
        slug: '/category/capstone-project',
      },
      items: [
        'capstone-project/project-overview',
        'capstone-project/system-design-integration',
        'capstone-project/implementation-steps',
        'capstone-project/testing-validation',
        'capstone-project/future-work',
      ],
    },
    {
      type: 'category',
      label: 'Appendices',
      link: {
        type: 'generated-index',
        title: 'Appendices',
        description: 'Supplementary materials for the book.',
        slug: '/category/appendices',
      },
      items: [
        'appendices/ros2-cheatsheet',
        'appendices/nvidia-isaac-api-reference',
        'appendices/troubleshooting-guide',
        'appendices/glossary',
      ],
    },
  ],
};

export default sidebars;